#!/usr/bin/env python3
"""
Injects Open Graph / Twitter Card meta tags into each broadcast, episode,
and work detail page, sourced from the same JSON that already drives the
rest of the site — so link previews in Slack/Discord/iMessage/etc. show
the right title, description, and image per page, without hand-writing
them 12+ times over and having them go stale.

Doesn't touch the existing <title> tag (some are hand-tuned) — reuses
whatever's already there for og:title/twitter:title. Everything this
script writes lives between marker comments, so re-running it replaces
its own block rather than duplicating tags.

Usage:
    python3 scripts/sync_social_meta.py
"""
import json
import os
import re
from xml.sax.saxutils import escape

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_URL = "https://daqhris.com/radio-hectolitre"

BEGIN = "<!-- BEGIN social-meta: generated by scripts/sync_social_meta.py, do not hand-edit -->"
END = "<!-- END social-meta -->"


def load(rel):
    with open(os.path.join(ROOT, rel)) as f:
        return json.load(f)


def abs_url(path_or_url):
    if re.match(r"^https?://", path_or_url):
        return path_or_url
    return f"{SITE_URL}/{path_or_url.lstrip('/')}"


def truncate(text, limit=200):
    text = " ".join(text.split())  # collapse whitespace/newlines
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0] + "…"


def extract_title(html):
    m = re.search(r"<title>(.*?)</title>", html, re.S)
    return m.group(1).strip() if m else "Radio Hectolitre"


def build_block(title, description, image, page_url):
    return "\n".join([
        BEGIN,
        f'  <meta property="og:type" content="website" />',
        f'  <meta property="og:site_name" content="Radio Hectolitre" />',
        f'  <meta property="og:url" content="{escape(page_url)}" />',
        f'  <meta property="og:title" content="{escape(title)}" />',
        f'  <meta property="og:description" content="{escape(description)}" />',
        f'  <meta property="og:image" content="{escape(image)}" />',
        f'  <meta name="twitter:card" content="summary_large_image" />',
        f'  <meta name="twitter:title" content="{escape(title)}" />',
        f'  <meta name="twitter:description" content="{escape(description)}" />',
        f'  <meta name="twitter:image" content="{escape(image)}" />',
        END,
    ])


def inject(html_path, description, image, page_url):
    with open(html_path) as f:
        html = f.read()

    title = extract_title(html)
    block = build_block(title, description, image, page_url)

    if BEGIN in html:
        html = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END),
            block,
            html,
            flags=re.S,
        )
    else:
        # Insert right after the <title> line.
        html = re.sub(
            r"(<title>.*?</title>\n)",
            r"\1" + block + "\n",
            html,
            count=1,
            flags=re.S,
        )

    with open(html_path, "w") as f:
        f.write(html)
    print(f"  {os.path.relpath(html_path, ROOT)}")


def main():
    updated = 0

    broadcasts = load("data/broadcasts/index.json")["broadcasts"]
    print("Broadcasts:")
    for b in broadcasts:
        detail = load(f"data/broadcasts/{b['id']}.json")
        hero = detail["hero"]
        inject(
            os.path.join(ROOT, b["href"]),
            description=hero.get("shortDescription", ""),
            image=abs_url(hero["heroImage"]),
            page_url=abs_url(b["href"]),
        )
        updated += 1

    episodes = load("data/episodes/index.json")["episodes"]
    print("Episodes:")
    for e in episodes:
        detail = load(f"data/episodes/{e['slug']}.json")
        subtitle = detail.get("subtitle", "")
        description = subtitle if len(subtitle) > 20 else truncate(
            (detail.get("synopsis") or [""])[0]
        )
        inject(
            os.path.join(ROOT, e["href"]),
            description=description,
            image=abs_url(detail["coverImage"]),
            page_url=abs_url(e["href"]),
        )
        updated += 1

    works = load("data/works/index.json")["works"]
    print("Works:")
    for w in works:
        detail = load(f"data/works/{w['slug']}.json")
        subtitle = detail.get("subtitle", "")
        description = subtitle if len(subtitle) > 20 else truncate(
            (detail.get("synopsis") or [""])[0]
        )
        inject(
            os.path.join(ROOT, w["href"]),
            description=description,
            image=abs_url(detail["coverImage"]),
            page_url=abs_url(w["href"]),
        )
        updated += 1

    print(f"\nUpdated {updated} page(s).")


if __name__ == "__main__":
    main()